Reduce image size by 50%: fixes

diff --git a/bin/browser_stack_version b/bin/browser_stack_version
--- a/bin/browser_stack_version
+++ b/bin/browser_stack_version
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+set -e
 
 # Example:
 #  BrowserStackLocal -version 2>&1
@@ -6,4 +7,8 @@
 
 # Example:
 #=> 5.3
-BrowserStackLocal -version 2>&1 | grep -Po '(?<=BrowserStack Local version )([a-z0-9\.]+)'
+if BrowserStackLocal -version >/dev/null 2>&1; then
+  BrowserStackLocal -version 2>&1 | grep -Po '(?<=BrowserStack Local version )([a-z0-9\.]+)'
+else
+  BrowserStackLocal -version #fail and show error
+fi
diff --git a/bin/chromedriver_version b/bin/chromedriver_version
--- a/bin/chromedriver_version
+++ b/bin/chromedriver_version
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+set -e
 
 # Example:
 #  chromedriver --version 2>&1
@@ -6,4 +7,8 @@
 
 # Example:
 #=> 2.21.371461
-chromedriver --version 2>&1 | grep -Po '(?<=ChromeDriver )([a-z0-9\.]+)'
+if chromedriver --version >/dev/null 2>&1; then
+  chromedriver --version 2>&1 | grep -Po '(?<=ChromeDriver )([a-z0-9\.]+)'
+else
+  chromedriver --version #fail and show error
+fi
diff --git a/bin/firefox_version b/bin/firefox_version
--- a/bin/firefox_version
+++ b/bin/firefox_version
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+set -e
 
 # Example:
 #  firefox -version 2>&1
@@ -6,4 +7,8 @@
 
 # Example:
 #=> 45.0.2
-firefox -version 2>&1 | grep -Po '(?<=Firefox )([a-z0-9\.]+)'
+if firefox -version >/dev/null 2>&1; then
+  firefox -version 2>&1 | grep -Po '(?<=Firefox )([a-z0-9\.]+)'
+else
+  firefox -version #fail and show error
+fi
diff --git a/bin/java_build_version b/bin/java_build_version
--- a/bin/java_build_version
+++ b/bin/java_build_version
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+set -e
 
 # Example OpenJDK 8:
 #  java -version 2>&1
@@ -16,4 +17,8 @@
 #=> 1.8.0_66-internal-b17
 # Example Oracle 9:
 #=> 9-ea+112
-java -version 2>&1 | grep -Po '(?<=Environment \(build )([a-z0-9\._\-\+]+)'
+if java -version >/dev/null 2>&1; then
+  java -version 2>&1 | grep -Po '(?<=Environment \(build )([a-z0-9\._\-\+]+)'
+else
+  java -version #fail and show error
+fi
diff --git a/bin/java_vendor_version b/bin/java_vendor_version
--- a/bin/java_vendor_version
+++ b/bin/java_vendor_version
@@ -1,9 +1,13 @@
 #!/usr/bin/env bash
+set -e
 
-if java -version 2>&1 | grep "OpenJ" >/dev/null; then
-  JAVA_VENDOR="OpenJDK"
+if java -version >/dev/null 2>&1; then
+  if java -version 2>&1 | grep "OpenJ" >/dev/null; then
+    JAVA_VENDOR="OpenJDK"
+  else
+    JAVA_VENDOR="Oracle"
+  fi
+  echo "${JAVA_VENDOR}"
 else
-  JAVA_VENDOR="Oracle"
+  java -version #fail and show error
 fi
-
-echo "${JAVA_VENDOR}"
diff --git a/bin/python_version b/bin/python_version
--- a/bin/python_version
+++ b/bin/python_version
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+set -e
 
 # Example:
 #  python --version 2>&1
@@ -6,4 +7,8 @@
 
 # Example:
 #=> 2.7.11
-python --version 2>&1 | grep -Po '(?<=Python )([a-z0-9\.]+)'
+if python --version; then
+  python --version 2>&1 | grep -Po '(?<=Python )([a-z0-9\.]+)'
+else
+  python --version #fail and show error
+fi
