Reduce image size by 50%: fixes

diff --git a/bin/chrome_stable_version b/bin/chrome_stable_version
--- a/bin/chrome_stable_version
+++ b/bin/chrome_stable_version
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+set -e
 
 # Example:
 #  google-chrome-stable --version 2>&1
@@ -6,4 +7,8 @@
 
 # Example:
 #=> 50.0.2661.75
-google-chrome-stable --version 2>&1 | grep -Po '(?<=Google Chrome )([a-z0-9\.]+)'
+if google-chrome-stable --version >/dev/null 2>&1; then
+  google-chrome-stable --version 2>&1 | grep -Po '(?<=Google Chrome )([a-z0-9\.]+)'
+else
+  google-chrome-stable --version #fail and show error
+fi
diff --git a/bin/chromedriver_commit_version b/bin/chromedriver_commit_version
--- a/bin/chromedriver_commit_version
+++ b/bin/chromedriver_commit_version
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
+set -e
 
 # Example:
 #=> 633e689b520b25f3e264a2ede6b74ccc23cb636a
-chromedriver --version 2>&1 | grep -Po '(?<=\s\()([a-z0-9]+)'
+if chromedriver --version >/dev/null 2>&1; then
+  chromedriver --version 2>&1 | grep -Po '(?<=\s\()([a-z0-9]+)'
+else
+  chromedriver --version #fail and show error
+fi
diff --git a/bin/firefox-for-sel-3_version b/bin/firefox-for-sel-3_version
--- a/bin/firefox-for-sel-3_version
+++ b/bin/firefox-for-sel-3_version
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+set -e
 
 # Example:
 #  firefox -version 2>&1
@@ -6,5 +7,9 @@
 
 # Example:
 #=> 49.0.1
-/home/seluser/firefox-for-sel-3/firefox \
-  -version 2>&1 | grep -Po '(?<=Firefox )([a-z0-9\.]+)'
+FFBIN="/home/seluser/firefox-for-sel-3/firefox"
+if ${FFBIN} >/dev/null 2>&1; then
+  ${FFBIN} -version 2>&1 | grep -Po '(?<=Firefox )([a-z0-9\.]+)'
+else
+  ${FFBIN} #fail and show error
+fi
diff --git a/bin/geckodriver_version b/bin/geckodriver_version
--- a/bin/geckodriver_version
+++ b/bin/geckodriver_version
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+set -e
 
 # Example:
 #  geckodriver --version 2>&1
@@ -9,4 +10,8 @@
 #=> 0.10.0
 CMD="geckodriver"
 [ "${USE_SELENIUM}" == "2" ] && CMD="/opt/geckodriver"
-${CMD} --version 2>&1 | grep -Po '(?<=geckodriver )([a-z0-9\.]+)'
+if ${CMD} --version >/dev/null 2>&1; then
+  ${CMD} --version 2>&1 | grep -Po '(?<=geckodriver )([a-z0-9\.]+)'
+else
+  ${CMD} --version #fail and show error
+fi
