Upgrade to Chrome to 46.0.2490.86

diff --git a/video-rec/bin/stop-video b/video-rec/bin/stop-video
--- a/video-rec/bin/stop-video
+++ b/video-rec/bin/stop-video
@@ -1,3 +1,42 @@
 #!/usr/bin/env bash
 
+# Exit immediately if a command exits with a non-zero status
+set -e
+
+# echo fn that outputs to stderr http://stackoverflow.com/a/2990533/511069
+echoerr() {
+  cat <<< "$@" 1>&2;
+}
+
+# print error and exit
+die () {
+  echoerr "ERROR: $1"
+  # if $2 is defined AND NOT EMPTY, use $2; otherwise, set to "3"
+  errnum=${2-3}
+  exit $errnum
+}
+
+# if $1 is defined AND NOT EMPTY, use $1; otherwise, set to "7s"
+WAIT_TIMEOUT=${1-7s}
+LOOP_SCRIPT_PATH="${BIN_UTILS}/wait-stop-video-rec.sh"
+
+if [ ! -f "${LOOP_SCRIPT_PATH}" ]; then
+  die "Need '${LOOP_SCRIPT_PATH}' to exist!"
+fi
+
+#----------------------
+# Stop video recording
+#----------------------
 supervisorctl -c /etc/supervisor/supervisord.conf stop video-rec
+
+# Avoid waiting forever using the `timeout` command
+if timeout --foreground ${WAIT_TIMEOUT} \
+     ${LOOP_SCRIPT_PATH}; then
+  echo "Video recording stopped"
+else
+  bash -c 'tail --lines=${TAIL_LOG_LINES} /var/log/sele/video-rec/*' || true
+  echo "" && echo "" && echo "==> errors <=="
+  bash -c 'selenium-grep.sh' || true
+
+  die "Were unable to stop video recording within '${WAIT_TIMEOUT}'"
+fi
